### ISSUE TITLE
The size of tensor a (4) must match the size of tensor b (36) at non-singleton dimension 3 error

### ISSUE THREAD

**Issue by Jihyun0510** [guanyingc/UPS-GCNet#15]
I downloaded your code but it keeps giving me this error

```
@@@@@@@@@@@@@@@@@@@@torch.cat(l_dirs_x, 0) torch.Size([96, 36, 4, 4])
@@@@@@@@@@@@@@@@@@@@torch.cat(l_dirs_x, 0).squeeze() torch.Size([96, 36, 4, 4])
@@@@@@@@@@@@@@@@@@@@dir_x and dir_y torch.Size([96, 36, 4, 4]) torch.Size([96, 36, 4, 4])
@@@@@@@@@@@@@@@@@@@@dirs_step torch.Size([36])
Traceback (most recent call last):
  File "run_model.py", line 20, in <module>
    main(args)
  File "run_model.py", line 15, in main
    test_utils.test(args, log, 'test', test_loader, model, 1, recorder)
  File "/home/wgus5950/UPS-GCNet/utils/test_utils.py", line 26, in test
    pred = model.forward(); 
  File "/home/wgus5950/UPS-GCNet/models/GCNet_model.py", line 81, in forward
    self.pred = self.GCNet(self.data)
  File "/home/wgus5950/miniconda3/envs/gcnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wgus5950/miniconda3/envs/gcnet/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/wgus5950/miniconda3/envs/gcnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wgus5950/UPS-GCNet/models/archs/GCNet.py", line 93, in forward
    L_Net1_pred = self.L_Net1(L_Net1_inputs)
  File "/home/wgus5950/miniconda3/envs/gcnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wgus5950/UPS-GCNet/models/archs/L_Net.py", line 141, in forward
    dirs = convert_dirs(l_dirs_x, l_dirs_y, self.opt, self.dirs_step)
  File "/home/wgus5950/UPS-GCNet/models/archs/L_Net.py", line 44, in convert_dirs
    x_idx = (x_prob * dirs_step).sum(1)
RuntimeError: The size of tensor a (4) must match the size of tensor b (36) at non-singleton dimension 3
```

what could be the reason??
I used diligent dataset.

**Comment by guanyingc** [comment]
Hi, what command did you run?

**Comment by Jihyun0510** [comment]
Thansk for your reply!

I re-cloned your git and it worked fine!
